services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      # For development stage build target shoulbe be: development
      # For production stage build target shoulbe be: production
      target: development
    env_file:
        - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_SECRET_REFRESH_KEY: ${JWT_SECRET_REFRESH_KEY}
      CRYPT_SALT: ${CRYPT_SALT}
      TOKEN_EXPIRE_TIME: ${TOKEN_EXPIRE_TIME}
      TOKEN_REFRESH_EXPIRE_TIME: ${TOKEN_REFRESH_EXPIRE_TIME}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    # To run in development mode: npm run start:dev
    # To run in production mode: npm run start:prod
    command: npm run start:dev
    restart: always
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      - home-library-app
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports: 
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - home-library-app

volumes:
  postgres-data:

networks:
  home-library-app: